# Generated by Django 3.1.1 on 2020-09-09 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname_first', models.CharField(max_length=32)),
                ('lastname_second', models.CharField(blank=True, max_length=32)),
                ('date_birth', models.DateField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('patient_type', models.IntegerField(choices=[(None, 'No definido'), (1, 'Residencia'), (2, 'Pediatría'), (3, 'Adultos')], default='No definido')),
                ('current_professional', models.ManyToManyField(blank=True, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
