# Generated by Django 3.1.1 on 2020-09-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='history_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.IntegerField(choices=[(None, 'No definido'), (1, 'Residencia'), (2, 'Pediatría'), (3, 'Adultos'), (4, 'Especiales')], default='No definido'),
        ),
        migrations.CreateModel(
            name='OtherPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=32)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=32)),
                ('duration', models.CharField(max_length=32)),
                ('frequency', models.CharField(max_length=32)),
                ('indications', models.TextField(max_length=256)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='allergic_patients', to='clinic.Medication'),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_medication',
            field=models.ManyToManyField(blank=True, related_name='other_medication', through='clinic.OtherPrescription', to='clinic.Medication'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, related_name='prescriptions', through='clinic.ClinicPrescription', to='clinic.Medication'),
        ),
    ]
