# Generated by Django 3.1.1 on 2020-09-20 14:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0002_auto_20200913_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=256)),
                ('comments', models.TextField(max_length=256)),
                ('associated_appointments', models.ManyToManyField(blank=True, related_name='_appointment_associated_appointments_+', to='clinic.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('timeslot', models.TimeField(choices=[(datetime.time(8, 0), 'H0800'), (datetime.time(8, 30), 'H0830'), (datetime.time(9, 0), 'H0900'), (datetime.time(9, 30), 'H0930'), (datetime.time(10, 0), 'H1000'), (datetime.time(10, 30), 'H1030'), (datetime.time(11, 0), 'H1100'), (datetime.time(11, 30), 'H1130'), (datetime.time(12, 0), 'H1200'), (datetime.time(12, 30), 'H1230'), (datetime.time(13, 0), 'H1300'), (datetime.time(13, 30), 'H1330'), (datetime.time(14, 0), 'H1400'), (datetime.time(14, 30), 'H1430'), (datetime.time(15, 0), 'H1500'), (datetime.time(15, 30), 'H1530'), (datetime.time(16, 0), 'H1600'), (datetime.time(16, 30), 'H1630'), (datetime.time(17, 0), 'H1700'), (datetime.time(17, 30), 'H1730'), (datetime.time(18, 0), 'H1800'), (datetime.time(18, 30), 'H1830'), (datetime.time(19, 0), 'H1900'), (datetime.time(19, 30), 'H1930'), (datetime.time(20, 0), 'H2000'), (datetime.time(20, 30), 'H2030')])),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prescriptions',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AppointmentTreatments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='clinic.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentProfessionalRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='professionals',
            field=models.ManyToManyField(through='clinic.AppointmentProfessionalRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicprescription',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='clinic.appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('date', 'patient'), name='unique_date_for_patient'),
        ),
    ]
